dorado_exec: "/work/microbiome/sw/dorado-v0.9.1/dorado-0.9.1-linux-x64/bin/dorado"
pod5_sample_list: "/work/microbiome/arctic/data/20240910/dorado-v0.9.0/test_snake/pod5_sample_list.txt"  # text file of POD5 sample filepaths
output_dir: "/" # Needs fixing, this is just an example config file
models_directory: "/work/microbiome/sw/dorado-v0.9.1/models"
